# Generated by Django 4.0.6 on 2022-08-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
