# Generated by Django 4.0.6 on 2022-10-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_loss_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={},
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_out',
            field=models.ImageField(null=True, upload_to='yolo_out'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
